########################################################
#
# Homeassistant main settings
#
########################################################
homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 112
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Berlin
  
  customize: !include customize.yaml  


########################################################
#
# Configuration files
#
########################################################
sensor: !include sensors.yaml
light: !include lights.yaml
group: !include groups.yaml
automation: !include_dir_merge_list automation

#script: !include_dir_named scripts
#device_tracker: !include devices_trackers.yaml

#camera: !include cameras
#sensor: !include_dir_merge_list sensors

#media_player: !include media_players.yaml
#scene: !include scenes.yaml
#notify: !include notify.yaml



########################################################
#
# Homematic
#
########################################################
homematic:
  interfaces:
    rf:
      #host: 127.0.0.1
      host: !secret ip_address
      resolvenames: json
      port: 2001



########################################################
#
# MQTT
#
########################################################
mqtt:
  # broker: core-mosquitto   # for hassio only
  broker: !secret ip_address
  port: 1883
  client_id: homeassistant_pi2
  keepalive: 60
  username: !secret mqtt_user
  password: !secret mqtt_password
  protocol: 3.1
  birth_message:
    topic: "tele/hassbian/LWT"
    payload: "Online"
    qos: 1
    retain: true
  will_message:
    topic: "tele/hassbian/LWT"
    payload: "Offline"
    qos: 1
    retain: true


########################################################
#
# Weather forecast
#
########################################################
# Track the sun
sun:

weather:
  - platform: darksky
    api_key: !secret darksky_api
    mode: daily




########################################################
#
# device tracker
#
########################################################
device_tracker:
  - platform: fritz
    interval_seconds: 30
    consider_home: 180
    new_device_defaults:
      track_new_devices: true


########################################################
#
# InfluxDB  (timeseries database)
#
########################################################
influxdb:
  host: !secret ip_address
  port: 8086
  database: home_assistant
  #username: home-assistant
  username: !secret influxdb_user
  password: !secret influxdb_password
  #ssl: true
  #verify_ssl: true
  max_retries: 3
  default_measurement: state
  #exclude:
  #  entities:
  #     - entity.id1
  #     - entity.id2
  #  domains:
  #     - automation
  #include:
  #  entities:
  #     - sensor.heizung_vl
  #     - sensor.heizung_rl
  #     - sensor.heizung_ww
  #tags:
  #  instance: prod
  #  source: hass


########################################################
#
# additional Pannels in HA
#
########################################################
panel_iframe:
  # router 
  router:
    title: 'Router'
    icon: mdi:router-wireless
    url: !secret router_url

  # Grafana (access from a tab in HA)
  grafana:
    title: 'Grafana'
    #icon: mdi:chart-timeline
    icon: mdi:chart-line
    url: !secret grafana_url

  # influxDB
  influxdb:
    title: 'InfluxDB'
    #icon: mdi:chart-areaspline
    icon: mdi:database-check
    url: !secret influx_url



########################################################
#
# History / Recorder
#
########################################################
history_graph:
  graph1:
    name: Heating
    entities:
      - sensor.heizung_vl
      - sensor.heizung_rl
    hours_to_show: 48
    refresh: 60

  graph2:
    name: Speedtest
    entities:
      - sensor.speedtest_download
      - sensor.speedtest_upload
    hours_to_show: 24
    refresh: 60


# Enables support for tracking state changes over time
history:

recorder:




########################################################
#
# HTTP
#
########################################################
http:
  # Uncomment this to add a password (recommended!)
  # since we support legacy_api_password the api_password for http is not needed anymore
  #api_password: !secret my_api_password   
  server_port: 8123
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123
  login_attempts_threshold: 3
  
  cors_allowed_origins:
    - https://google.com
    - https://home-assistant.io



########################################################
#
# additional platforms
#
########################################################

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true

# Discover some devices automatically
# see: https://www.home-assistant.io/components/discovery/
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:


# View all events in a logbook
logbook:


# Enables the frontend
frontend:

# Enables configuration UI
config:

#ios:

#map:

# Allow to use python_scripts
#python_script:

# Text to speech
tts:
  - platform: google
    language: 'de'



########################################################
#
# ZONES
#
########################################################
zone 1:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  radius: 100
  icon: mdi:home

zone 2:
  name: JD@Work
  latitude: !secret work_latitude
  longitude: !secret work_longitude
  radius: 500
  icon: mdi:briefcase


